### ISSUE TITLE
still have aws credentials issue

### ISSUE THREAD

**Issue by yilewang** [brain-score/vision#497]
Hi I think I still have the `Exception: [ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden'), ClientError('An error occurred (403) when calling the HeadObject operation: Forbidden')]
` issue when i want to run certain type of benchmark, such as `Rajalingham2018-i2n`.

I have set up my aws credential, and I added an additional policy to make sure I will have HeadObject operation. I am wondering do you know how to solve it?

Thank you!

**Comment by yilewang** [comment]
#96

**Comment by kvfairchild** [comment]
Hi @yilewang,

Some benchmarks are private access only, e.g. for holdout data (you can check in the test files to see if tests for a particular identifier are marked `private_access`). `Rajalingham2018-i2n` does have a public option: `Rajalingham2018public-i2n`. 

We're currently working on documentation that will clarify this distinction and list which identifiers are public vs. private, so hopefully that will help prevent this confusion in the future.

Don't hesitate to let me know if you have further questions, otherwise I'll mark this issue as resolved.

**Comment by yilewang** [comment]
thank you @kvfairchild ! that's really helpful!
