### ISSUE TITLE
Brain Score Logs

### ISSUE THREAD

**Issue by amirozhan** [brain-score/vision#522]
Hello, I recently submitted a model, however I don't see any data regarding the submitted model. Would it show up after 24 hours?

**Comment by mike-ferguson** [comment]
Hi @amirozhan, thanks for reaching out! Normally you will get an email with a link containing your build log, where you can then check the status of your model. On a successful scoring run, your model score will then show up on the website leaderboard within 24 hours. 

However, right now do to our team still working out some kinks in the 2.0 refactor, this might not happen yet. 

So, I went ahead and  manually looked up your submission to see what happened to your model. I see three submissions, all from January 3 2024. From these logs, it looks like your model might have errored due to some issues with the 1.x version Tensorflow. Please see the log from your last build [here](http://braintree.mit.edu:8080/job/run_benchmarks/12407/parsed_console/), as well as Issue #526 that addresses some 1.x Tensorflow stuff. Please let me know if you have any other questions, we are happy to help.
