### ISSUE TITLE
Jenkins is skipping all tests

### ISSUE THREAD

**Issue by benlonnqvist** [brain-score/vision#668]
On some PRs, Jenkins is skipping all tests and is marked as passing, even though no tests or plugin tests were ran. See for example #536, with [Jenkins plugin logs here](http://braintree.mit.edu:8080/job/unittest_plugins/862/) and [Jenkins logs here](http://braintree.mit.edu:8080/job/unittest_brainscore/1981/).

**Comment by kvfairchild** [comment]
The failing tests look like issues that might be fixed by cleaning up `conda`. Currently working on that; unfortunately you'll need to retrigger the tests by closing and reopening the PR.

The bigger problem appears to be that the Jenkins builds weren't getting marked as failures despite the errors. This should be fixed now.

**Comment by benlonnqvist** [comment]
Thank you @kvfairchild!
